### PR TITLE
download broadcasts to named subdirectory

### PR DESCRIPTION
**Pull request by zp**
Creates a subfolder in the ````settings.downloadPath```` with the current format ````user_id (username)```` and downloads broadcasts into it. 

It will auto fall-back to the base ````settings.downloadPath```` path if user_id and user_name are null. (for manual downloading)

example:

Went with user_id first for sorting purposes, incase a user changes their username, you can easily sort and compare old/new usernames, then username in parentheses for ease of use and search-ability

I think I covered all download cases, seems to work for everything I tested it on (auto caps, manual caps, replays, etc)

I've only tested on Windows.

### CODE REVIEW

**Comment by Pmmlabs** [comment]
Good job! Thanks!

**Comment by kkoepke** [comment]
@Pmmlabs maybe we can get a new precompiled release 1.7.1 with these new changes?

**Comment by Vol-2016** [comment]
try 
https://github.com/Pmmlabs/OpenPeriscope/wiki#how-to-update-portable-version-exe

**Comment by Pmmlabs** [comment]
This changes are in [v1.8](https://github.com/Pmmlabs/OpenPeriscope/releases/tag/v1.8)

**Pull request merged**
